/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 files/blender/me3.glb --transform --types -o src/models/Scenes.tsx 
Files: files/blender/me3.glb [6.62MB] > C:\xampp\htdocs\cv-3d\src\models\me3-transformed.glb [2.48MB] (63%)
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";

type ActionName =
  | "F_Standing_Idle_001.001"
  | "F_Standing_Idle_Variations_001.001"
  | "F_Standing_Idle_Variations_008.001"
  | "F_Standing_Idle_Variations_009.001"
  | "F_Talking_Variations_001.001"
  | "F_Talking_Variations_001.004"
  | "F_Talking_Variations_004.001"
  | "M_Standing_Expressions_001.001"
  | "M_Standing_Expressions_001.004"
  | "M_Standing_Expressions_001.005"
  | "Walk_N.001"
  | "Walk_N.004"
  | "Walk_N.005"
  | "Icosphere.002Action";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    geometry_0001: THREE.Mesh;
    geometry_0001_1: THREE.Mesh;
    InnerRing: THREE.Mesh;
    Renderer_Body002: THREE.SkinnedMesh;
    Renderer_Hair002: THREE.SkinnedMesh;
    Renderer_Outfit_Bottom002: THREE.SkinnedMesh;
    Renderer_Outfit_Footwear002: THREE.SkinnedMesh;
    Renderer_Outfit_Top002: THREE.SkinnedMesh;
    Renderer_EyeLeft002: THREE.SkinnedMesh;
    Renderer_EyeRight002: THREE.SkinnedMesh;
    Renderer_Head002: THREE.SkinnedMesh;
    Renderer_Teeth002: THREE.SkinnedMesh;
    Soleil: THREE.Mesh;
    Sphere: THREE.Mesh;
    Icosphere002: THREE.Mesh;
    P1_Water001_Clouds001_0: THREE.Mesh;
    P1_Water001_HUD_B002_0: THREE.Mesh;
    P1_Water001_Lava002_0: THREE.Mesh;
    Hips: THREE.Bone;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    PaletteMaterial003: THREE.MeshStandardMaterial;
    ["Material_Body.001"]: THREE.MeshStandardMaterial;
    ["Material_Hair.001"]: THREE.MeshStandardMaterial;
    ["Material_Outfit_Bottom.001"]: THREE.MeshStandardMaterial;
    ["Material_Outfit_Footwear.001"]: THREE.MeshStandardMaterial;
    ["Material_Outfit_Top.001"]: THREE.MeshStandardMaterial;
    ["Material_EyeRight.001"]: THREE.MeshStandardMaterial;
    ["Material_Head.001"]: THREE.MeshStandardMaterial;
    ["Material_Teeth.001"]: THREE.MeshStandardMaterial;
    ["Material.011"]: THREE.MeshStandardMaterial;
    PaletteMaterial006: THREE.MeshStandardMaterial;
    PaletteMaterial004: THREE.MeshStandardMaterial;
    PaletteMaterial005: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const group = React.useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF("/me3-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001">
          <primitive object={nodes.Hips} />
          <group name="Base">
            <mesh
              name="geometry_0001"
              geometry={nodes.geometry_0001.geometry}
              material={materials.PaletteMaterial001}
            />
            <mesh
              name="geometry_0001_1"
              geometry={nodes.geometry_0001_1.geometry}
              material={materials.PaletteMaterial002}
            />
          </group>
          <mesh
            name="InnerRing"
            geometry={nodes.InnerRing.geometry}
            material={materials.PaletteMaterial003}
          />
          <skinnedMesh
            name="Renderer_Body002"
            geometry={nodes.Renderer_Body002.geometry}
            material={materials["Material_Body.001"]}
            skeleton={nodes.Renderer_Body002.skeleton}
          />
          <skinnedMesh
            name="Renderer_Hair002"
            geometry={nodes.Renderer_Hair002.geometry}
            material={materials["Material_Hair.001"]}
            skeleton={nodes.Renderer_Hair002.skeleton}
          />
          <skinnedMesh
            name="Renderer_Outfit_Bottom002"
            geometry={nodes.Renderer_Outfit_Bottom002.geometry}
            material={materials["Material_Outfit_Bottom.001"]}
            skeleton={nodes.Renderer_Outfit_Bottom002.skeleton}
          />
          <skinnedMesh
            name="Renderer_Outfit_Footwear002"
            geometry={nodes.Renderer_Outfit_Footwear002.geometry}
            material={materials["Material_Outfit_Footwear.001"]}
            skeleton={nodes.Renderer_Outfit_Footwear002.skeleton}
          />
          <skinnedMesh
            name="Renderer_Outfit_Top002"
            geometry={nodes.Renderer_Outfit_Top002.geometry}
            material={materials["Material_Outfit_Top.001"]}
            skeleton={nodes.Renderer_Outfit_Top002.skeleton}
          />
          <skinnedMesh
            name="Renderer_EyeLeft002"
            geometry={nodes.Renderer_EyeLeft002.geometry}
            material={materials["Material_EyeRight.001"]}
            skeleton={nodes.Renderer_EyeLeft002.skeleton}
            morphTargetDictionary={
              nodes.Renderer_EyeLeft002.morphTargetDictionary
            }
            morphTargetInfluences={
              nodes.Renderer_EyeLeft002.morphTargetInfluences
            }
          />
          <skinnedMesh
            name="Renderer_EyeRight002"
            geometry={nodes.Renderer_EyeRight002.geometry}
            material={materials["Material_EyeRight.001"]}
            skeleton={nodes.Renderer_EyeRight002.skeleton}
            morphTargetDictionary={
              nodes.Renderer_EyeRight002.morphTargetDictionary
            }
            morphTargetInfluences={
              nodes.Renderer_EyeRight002.morphTargetInfluences
            }
          />
          <skinnedMesh
            name="Renderer_Head002"
            geometry={nodes.Renderer_Head002.geometry}
            material={materials["Material_Head.001"]}
            skeleton={nodes.Renderer_Head002.skeleton}
            morphTargetDictionary={nodes.Renderer_Head002.morphTargetDictionary}
            morphTargetInfluences={nodes.Renderer_Head002.morphTargetInfluences}
          />
          <skinnedMesh
            name="Renderer_Teeth002"
            geometry={nodes.Renderer_Teeth002.geometry}
            material={materials["Material_Teeth.001"]}
            skeleton={nodes.Renderer_Teeth002.skeleton}
            morphTargetDictionary={
              nodes.Renderer_Teeth002.morphTargetDictionary
            }
            morphTargetInfluences={
              nodes.Renderer_Teeth002.morphTargetInfluences
            }
          />
        </group>
        <mesh
          name="Soleil"
          geometry={nodes.Soleil.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          name="Sphere"
          geometry={nodes.Sphere.geometry}
          material={materials.PaletteMaterial006}
        />
        <mesh
          name="Icosphere002"
          geometry={nodes.Icosphere002.geometry}
          material={materials.PaletteMaterial002}
          position={[-5.307, 7.457, -1.018]}
          scale={1.934}
        />
        <mesh
          name="P1_Water001_Clouds001_0"
          geometry={nodes.P1_Water001_Clouds001_0.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          name="P1_Water001_HUD_B002_0"
          geometry={nodes.P1_Water001_HUD_B002_0.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          name="P1_Water001_Lava002_0"
          geometry={nodes.P1_Water001_Lava002_0.geometry}
          material={materials.PaletteMaterial005}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/me3-transformed.glb");
